import { motion } from 'framer-motion'
import { Link } from 'react-router-dom'
import {
  Zap, FileText, Code2, MessageSquare, Trophy,
  LayoutDashboard, ArrowRight, CheckCircle, Star
} from 'lucide-react'

const features = [
  {
    icon: FileText,
    title: 'Resume AI Screening',
    desc: 'Automatically rank and evaluate resumes using LLM + vector similarity matching.',
    color: 'from-blue-500 to-indigo-600',
  },
  {
    icon: Code2,
    title: 'Coding Assessment IDE',
    desc: 'In-browser Monaco editor powered by Judge0 for real code execution in 40+ languages.',
    color: 'from-purple-500 to-pink-600',
  },
  {
    icon: MessageSquare,
    title: 'AI Interview Engine',
    desc: 'Dynamic adaptive questions generated by Groq LLM based on candidate responses.',
    color: 'from-emerald-500 to-teal-600',
  },
  {
    icon: Trophy,
    title: 'Candidate Ranking',
    desc: 'Composite scoring engine that ranks candidates across resume, code, and interview.',
    color: 'from-amber-500 to-orange-600',
  },
  {
    icon: LayoutDashboard,
    title: 'Recruiter Dashboard',
    desc: 'Full pipeline view with analytics, job management, and one-click candidate actions.',
    color: 'from-rose-500 to-red-600',
  },
]

const stats = [
  { value: '10x', label: 'Faster Screening' },
  { value: '94%', label: 'Accuracy Rate' },
  { value: '40+', label: 'Languages Supported' },
  { value: '∞',   label: 'Free Tier Eligible' },
]

const fadeUp = {
  hidden: { opacity: 0, y: 30 },
  visible: (i = 0) => ({
    opacity: 1, y: 0,
    transition: { delay: i * 0.1, duration: 0.6, ease: 'easeOut' }
  }),
}

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-surface-900 text-white">
      {/* Ambient background */}
      <div className="fixed inset-0 pointer-events-none overflow-hidden">
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[800px] h-[500px] bg-primary-600/10 rounded-full blur-[120px]" />
        <div className="absolute bottom-0 right-0 w-[500px] h-[400px] bg-accent-500/8 rounded-full blur-[100px]" />
      </div>

      {/* Navbar */}
      <nav className="relative z-10 flex items-center justify-between px-8 py-5 max-w-7xl mx-auto">
        <div className="flex items-center gap-3">
          <div className="w-9 h-9 rounded-xl bg-gradient-to-br from-primary-500 to-accent-500 flex items-center justify-center shadow-lg shadow-primary-900/60">
            <Zap className="w-5 h-5 text-white" />
          </div>
          <span className="font-bold text-xl text-white">NextHire <span className="glow-text">AI</span></span>
        </div>
        <div className="flex items-center gap-3">
          <Link to="/login" className="btn-ghost">Sign In</Link>
          <Link to="/register" className="btn-primary">Get Started <ArrowRight size={15} /></Link>
        </div>
      </nav>

      {/* Hero */}
      <section className="relative z-10 max-w-5xl mx-auto text-center px-6 pt-24 pb-20">
        <motion.div
          initial="hidden" animate="visible" variants={fadeUp}
          className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary-500/10 border border-primary-500/25 text-primary-300 text-sm font-medium mb-8"
        >
          <Star size={14} className="fill-primary-400 text-primary-400" />
          Powered by Groq LLM + Pinecone Vector Search
        </motion.div>

        <motion.h1
          initial="hidden" animate="visible" custom={1} variants={fadeUp}
          className="text-6xl md:text-7xl font-extrabold leading-tight mb-6"
        >
          Hire the Best Talent
          <br />
          <span className="glow-text">10x Faster with AI</span>
        </motion.h1>

        <motion.p
          initial="hidden" animate="visible" custom={2} variants={fadeUp}
          className="text-xl text-slate-400 max-w-2xl mx-auto mb-10 text-balance"
        >
          An end-to-end AI hiring platform — from resume screening to live coding assessments
          and adaptive AI interviews. 100% free-tier infrastructure.
        </motion.p>

        <motion.div
          initial="hidden" animate="visible" custom={3} variants={fadeUp}
          className="flex flex-col sm:flex-row items-center justify-center gap-4"
        >
          <Link to="/register" className="btn-primary text-base px-7 py-3.5">
            Start Hiring Free <ArrowRight size={17} />
          </Link>
          <Link to="/login" className="btn-secondary text-base px-7 py-3.5">
            Live Demo
          </Link>
        </motion.div>

        {/* Checklist */}
        <motion.div
          initial="hidden" animate="visible" custom={4} variants={fadeUp}
          className="flex flex-wrap items-center justify-center gap-x-6 gap-y-2 mt-10 text-slate-400 text-sm"
        >
          {['Free Forever Plan', 'No Credit Card Required', 'Real AI Integration', 'Open Source Friendly'].map(item => (
            <span key={item} className="flex items-center gap-1.5">
              <CheckCircle size={14} className="text-accent-400" /> {item}
            </span>
          ))}
        </motion.div>
      </section>

      {/* Stats */}
      <section className="relative z-10 max-w-4xl mx-auto px-6 pb-16">
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          {stats.map((s, i) => (
            <motion.div
              key={s.label} initial="hidden" whileInView="visible" custom={i} variants={fadeUp} viewport={{ once: true }}
              className="card text-center"
            >
              <p className="text-4xl font-extrabold glow-text mb-1">{s.value}</p>
              <p className="text-slate-400 text-sm">{s.label}</p>
            </motion.div>
          ))}
        </div>
      </section>

      {/* Features */}
      <section className="relative z-10 max-w-6xl mx-auto px-6 pb-24">
        <motion.h2
          initial="hidden" whileInView="visible" variants={fadeUp} viewport={{ once: true }}
          className="section-title text-center mb-12"
        >
          Everything you need to hire smarter
        </motion.h2>
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-5">
          {features.map((f, i) => (
            <motion.div
              key={f.title} initial="hidden" whileInView="visible" custom={i * 0.5} variants={fadeUp} viewport={{ once: true }}
              className="card group cursor-pointer"
            >
              <div className={`w-11 h-11 rounded-xl bg-gradient-to-br ${f.color} flex items-center justify-center mb-4 shadow-lg group-hover:scale-110 transition-transform duration-300`}>
                <f.icon className="w-5 h-5 text-white" />
              </div>
              <h3 className="font-semibold text-white mb-2">{f.title}</h3>
              <p className="text-slate-400 text-sm leading-relaxed">{f.desc}</p>
            </motion.div>
          ))}
        </div>
      </section>

      {/* CTA */}
      <section className="relative z-10 max-w-3xl mx-auto px-6 pb-24 text-center">
        <div className="card-glow gradient-border p-12">
          <h2 className="text-4xl font-bold text-white mb-4">Ready to transform hiring?</h2>
          <p className="text-slate-400 mb-8">Join thousands of recruiters using NextHire AI to find perfect candidates faster.</p>
          <Link to="/register" className="btn-primary text-base px-8 py-3.5">
            Get Started for Free <ArrowRight size={17} />
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="relative z-10 border-t border-white/[0.07] py-6 text-center text-slate-500 text-sm">
        © 2025 NextHire AI · Built with Groq, Pinecone, MongoDB & ❤️
      </footer>
    </div>
  )
}
